# Numpy

In [112]:
#Check version of numpy library
import numpy
numpy.__version__

'1.26.0'

In [113]:
#Importing numpy as an alias(short name)
import numpy as np #alias in python is similar to calling someone with a nickname

In [114]:
#np.zeros() creates an array of 0s of specific length 
#here we create a zeros array of length 5
zeros_array=np.zeros(5,dtype="int") 
zeros_array

array([0, 0, 0, 0, 0])

In [115]:
#np.ones() creates an array of 1s of specific length 
#here we create a zeros array of length 5
ones_array=np.ones(5,dtype="int") 
ones_array

array([1, 1, 1, 1, 1])

In [116]:
#np.full() is used to create an array of given dimesnion with all elements having same 
#here we create a 2X3 array of just 5s
five_array=np.full((2,3),5)
five_array

array([[5, 5, 5],
       [5, 5, 5]])

In [117]:
#np.arange() gives an array in a linear sequence from starting value to ending value with a step value in between(if specified)
#starting value is included and ending value is not included.
#here we create a array from 0 to 20 with a step of 2
two_tables=np.arange(2,22,2)
two_tables

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [118]:
#np.linspace() gives an evenly spaced array from a starting point to an ending point of a specific length
#here we create a array of 8 elements from 0 to 2 that are evenly spaced
evenly_spaced=np.linspace(0,1,5)
evenly_spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [119]:
#np.random.random() is used to create an array of random values between 0 and 1(probabilities) of specific dimensions 
#creating a random_array of 2X2 dimensions with values between 0 and 1
random_array=np.random.random((2,2))
random_array

array([[0.83796147, 0.72021726],
       [0.24786748, 0.62464272]])

In [120]:
#np.random.random() is used to create an array of random integer values between a given range of specific dimensions 
#creating a random array of integers between 0 and 10(9 is not included) of 2X3 dimensions 
random_single_digits_array=np.random.randint(0,10,(2,3))
random_single_digits_array

array([[9, 7, 6],
       [1, 5, 9]])

In [121]:
# List of cloud technologies in 2023
cloud_2023 = ['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare', 'Google Cloud','Digital Ocean',
               'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH',
               'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack',
               'IBM Cloud Or Watson', 'Scaleway', 'Colocation', 'Microsoft Azure']

#list of all votes for each cloud platform
votes_raw=[33818, 29479, 654, 1185,10761, 8550, 628, 486,10599, 8326, 420, 621,16592, 13304, 652, 866,
9299, 7838, 247, 393,8358, 6535, 492, 418,7431, 5727, 487, 392,6228, 4708, 498, 330,4964, 3584, 262, 396,3069, 2465, 67, 184,
2755, 2104, 125, 167,2379, 1889, 63, 137,2378, 1912, 76, 126,1810, 1146, 123, 190,1671, 1432, 22, 66,1649, 1342, 72, 79,1357, 1021, 55, 94,
1287, 920, 132, 69,1076, 802, 53, 78,801, 571, 53, 70,628, 520, 0, 31,7, 385, 20, 30,18105, 15441, 370, 714]

In [122]:
#The first thing we should do is to convert the lists to numpy arrays.To convert python lists to numpy arrays we use np.array() method.
print("Data type of data:",type(cloud_2023))

Data type of data: <class 'list'>


In [123]:
#Numpy array definitions 
import numpy as np
cloud_2023_array=np.array(cloud_2023)
votes_raw_array=np.array(votes_raw)
print(cloud_2023_array)
print(votes_raw_array)

['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean' 'Heroku' 'Vercel' 'Netlify' 'VMware' 'Hetzner'
 'Linode, now Akamai' 'Managed Hosting' 'OVH'
 'Oracle Cloud Infrastructure (OCI)' 'OpenShift' 'Fly.io' 'Vultr' 'Render'
 'OpenStack' 'IBM Cloud Or Watson' 'Scaleway' 'Colocation'
 'Microsoft Azure']
[33818 29479   654  1185 10761  8550   628   486 10599  8326   420   621
 16592 13304   652   866  9299  7838   247   393  8358  6535   492   418
  7431  5727   487   392  6228  4708   498   330  4964  3584   262   396
  3069  2465    67   184  2755  2104   125   167  2379  1889    63   137
  2378  1912    76   126  1810  1146   123   190  1671  1432    22    66
  1649  1342    72    79  1357  1021    55    94  1287   920   132    69
  1076   802    53    78   801   571    53    70   628   520     0    31
     7   385    20    30 18105 15441   370   714]


In [124]:
#Numpy attributes
print("Data type of list:",type(cloud_2023_array))
print("Number of cloud services in 2023 survey:",cloud_2023_array.size)
print("Shape of cloud 2023 array:",cloud_2023_array.shape)
print("Data type of each element of cloud 2023 array:",cloud_2023_array.dtype)
print("Data type of each element of total votes array:",votes_raw_array.dtype)
print("Number of dimesnions in cloud 2023 array:",cloud_2023_array.ndim)

Data type of list: <class 'numpy.ndarray'>
Number of cloud services in 2023 survey: 23
Shape of cloud 2023 array: (23,)
Data type of each element of cloud 2023 array: <U33
Data type of each element of total votes array: int32
Number of dimesnions in cloud 2023 array: 1


In [125]:
#type casting from int32 to int16
votes_raw_array_16bit_integer=np.array(votes_raw_array,dtype=np.int16)
print("Data type of each element of other votes array:",votes_raw_array_16bit_integer.dtype)

Data type of each element of other votes array: int16


In [126]:
#upcasting
#What happens if we put non float numbers in an integer array
#if possible python will convert the values to the given dtype
int32_array=np.array([1.6,0,2,9,3,True],dtype="int")
int32_array

array([1, 0, 2, 9, 3, 1])

In [151]:
#we need to reshape this massive singular array to a multi dimensional array
test_array=np.array([33818,29479,654,1185,18105,15441,370,714])
print(test_array.shape)
reshaped_array=np.reshape(test_array,(2,4))#we want this format [[33818,29479,654,1185],[18105,15441,370,714]] which is 2 rows 4 columns
print(reshaped_array)

(8,)
[[33818 29479   654  1185]
 [18105 15441   370   714]]


In [152]:
#Reshaping the array to a more suitable format
merged_votes_array=np.reshape(votes_raw_array,(len(votes_raw_array)//4,4))
print(merged_votes_array)
print("Shape of reshaped arrays:",merged_votes_array.shape)

[[33818 29479   654  1185]
 [10761  8550   628   486]
 [10599  8326   420   621]
 [16592 13304   652   866]
 [ 9299  7838   247   393]
 [ 8358  6535   492   418]
 [ 7431  5727   487   392]
 [ 6228  4708   498   330]
 [ 4964  3584   262   396]
 [ 3069  2465    67   184]
 [ 2755  2104   125   167]
 [ 2379  1889    63   137]
 [ 2378  1912    76   126]
 [ 1810  1146   123   190]
 [ 1671  1432    22    66]
 [ 1649  1342    72    79]
 [ 1357  1021    55    94]
 [ 1287   920   132    69]
 [ 1076   802    53    78]
 [  801   571    53    70]
 [  628   520     0    31]
 [    7   385    20    30]
 [18105 15441   370   714]]
Shape of reshaped arrays: (23, 4)


In [153]:
import numpy as np
print("Data type of list:",type(merged_votes_array))
print("Number of voting groups in 2023 survey:",merged_votes_array.size)
print("Shape of merged_voting array:",merged_votes_array.shape)
print("Data type of each element of technologies_2023 array:",merged_votes_array.dtype)
print("Number of dimesnions in technologies 2023 array:",merged_votes_array.ndim)

Data type of list: <class 'numpy.ndarray'>
Number of voting groups in 2023 survey: 92
Shape of merged_voting array: (23, 4)
Data type of each element of technologies_2023 array: int32
Number of dimesnions in technologies 2023 array: 2


In [154]:
#splitting the merged votes array to seprate array of voters
total_votes_array=merged_votes_array[:,0]
professional_votes_array=merged_votes_array[:,1]
beginner_votes_array=merged_votes_array[:, 2]
other_votes_array=merged_votes_array[:, 3]
print("Total votes array:",total_votes_array)
print("\n\n")
print("Professional votes array:",professional_votes_array)
print("\n\n")
print("Beginner votes array:",beginner_votes_array)
print("\n\n")
print("Other votes array:",other_votes_array)

Total votes array: [33818 10761 10599 16592  9299  8358  7431  6228  4964  3069  2755  2379
  2378  1810  1671  1649  1357  1287  1076   801   628     7 18105]



Professional votes array: [29479  8550  8326 13304  7838  6535  5727  4708  3584  2465  2104  1889
  1912  1146  1432  1342  1021   920   802   571   520   385 15441]



Beginner votes array: [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Other votes array: [1185  486  621  866  393  418  392  330  396  184  167  137  126  190
   66   79   94   69   78   70   31   30  714]


In [155]:
#Corresponding vote values for a cloud service
print("Cloud service:",cloud_2023_array[1])
print("Total number of votes:",total_votes_array[1])
print("Professional programmers votes:",professional_votes_array[1])
print("Beginner programmers votes:",beginner_votes_array[1])
print("other programmers votes:",other_votes_array[1])

Cloud service: Firebase
Total number of votes: 10761
Professional programmers votes: 8550
Beginner programmers votes: 628
other programmers votes: 486


In [156]:
#Corresponding vote values for first five cloud service(not sorted!)
print("Cloud service:",cloud_2023_array[:5])
print("Total number of votes:",total_votes_array[:5])
print("Professional programmers votes:",professional_votes_array[:5])
print("Beginner programmers votes:",beginner_votes_array[:5])
print("Other programmers votes:",other_votes_array[:5])

Cloud service: ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean']
Total number of votes: [33818 10761 10599 16592  9299]
Professional programmers votes: [29479  8550  8326 13304  7838]
Beginner programmers votes: [654 628 420 652 247]
Other programmers votes: [1185  486  621  866  393]


In [157]:
#Corresponding vote values for last five cloud service(not sorted!)
print(cloud_2023_array)
print("\n\n")
print("Cloud services from position 2 to 5:",cloud_2023_array[2:6])
print("\n\n")
print("Even indexed Cloud services:",cloud_2023_array[::2])
print("\n\n")
print("Cloud services in reverse:",cloud_2023_array[::-1])
print("\n\n")

['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean' 'Heroku' 'Vercel' 'Netlify' 'VMware' 'Hetzner'
 'Linode, now Akamai' 'Managed Hosting' 'OVH'
 'Oracle Cloud Infrastructure (OCI)' 'OpenShift' 'Fly.io' 'Vultr' 'Render'
 'OpenStack' 'IBM Cloud Or Watson' 'Scaleway' 'Colocation'
 'Microsoft Azure']



Cloud services from position 2 to 5: ['Cloudflare' 'Google Cloud' 'Digital Ocean' 'Heroku']



Even indexed Cloud services: ['Amazon Web Services (AWS)' 'Cloudflare' 'Digital Ocean' 'Vercel'
 'VMware' 'Linode, now Akamai' 'OVH' 'OpenShift' 'Vultr' 'OpenStack'
 'Scaleway' 'Microsoft Azure']



Cloud services in reverse: ['Microsoft Azure' 'Colocation' 'Scaleway' 'IBM Cloud Or Watson'
 'OpenStack' 'Render' 'Vultr' 'Fly.io' 'OpenShift'
 'Oracle Cloud Infrastructure (OCI)' 'OVH' 'Managed Hosting'
 'Linode, now Akamai' 'Hetzner' 'VMware' 'Netlify' 'Vercel' 'Heroku'
 'Digital Ocean' 'Google Cloud' 'Cloudflare' 'Firebase'
 'Amazon Web Services (AWS)']





In [133]:
#example of making changes in numpy slices and python lists
l=[1,2,3,4,5]
arr=np.array([1,2,3,4,5])
l[0:3][1]=0 #In the list,we take slice of first 3 elements and then update the first element in the slice as 0. [1,2,3]-> [0,2,3]
arr[0:3][1]=0 #In the array we do the same ,we take slice of first 3 elements and then update the first element in the slice as 0.
print(l,arr)

#Now we can store these slices as seperate arrays for futher modifications or analysis without disturbing the original array.This is done 
#Using the copy() method
arr=np.array([1,2,3,4,5])

#with copy method 
even_elements_array=arr[0:5:2].copy()
even_elements_array[0]=2
print(even_elements_array,arr)

#without copy method(original array changes)
even_elements_array=arr[0:5:2]
even_elements_array[0]=2
print(even_elements_array,arr)

[1, 2, 3, 4, 5] [1 0 3 4 5]
[2 3 5] [1 2 3 4 5]
[2 3 5] [2 2 3 4 5]


In [136]:
#similarly we do for the raw_votes array
merged_votes_array=np.reshape(votes_raw,(23,4))
print(merged_votes_array)
print("Number of dimensions in the array:",merged_votes_array.ndim)
print("Shape and dimensions of the array:",merged_votes_array.shape)
print("Number of elements in the array:",merged_votes_array.size)
print("Data type of elements in the array:",merged_votes_array.dtype)

[[33818 29479   654  1185]
 [10761  8550   628   486]
 [10599  8326   420   621]
 [16592 13304   652   866]
 [ 9299  7838   247   393]
 [ 8358  6535   492   418]
 [ 7431  5727   487   392]
 [ 6228  4708   498   330]
 [ 4964  3584   262   396]
 [ 3069  2465    67   184]
 [ 2755  2104   125   167]
 [ 2379  1889    63   137]
 [ 2378  1912    76   126]
 [ 1810  1146   123   190]
 [ 1671  1432    22    66]
 [ 1649  1342    72    79]
 [ 1357  1021    55    94]
 [ 1287   920   132    69]
 [ 1076   802    53    78]
 [  801   571    53    70]
 [  628   520     0    31]
 [    7   385    20    30]
 [18105 15441   370   714]]
Number of dimensions in the array: 2
Shape and dimensions of the array: (23, 4)
Number of elements in the array: 92
Data type of elements in the array: int32


In [137]:
import numpy as np
def compute_non_professional_votes(beginner_votes_array,other_votes_array):
    output = np.empty(len(beginner_votes_array))
    for i in range(len(beginner_votes_array)):
        output[i]=beginner_votes_array[i]+other_votes_array[i]
    return output

%timeit compute_non_professional_votes(beginner_votes_array,other_votes_array)
%timeit (beginner_votes_array+other_votes_array)

16.3 µs ± 786 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.13 µs ± 47.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [138]:
#Array arithmetic in Numpy
print("Original array:",beginner_votes_array)
print("\n\n")
print("Adding 2 to all elements:",beginner_votes_array+2)
print("\n\n")
print("Dividing all elements by 2(normal)",beginner_votes_array/2)
print("\n\n")
floor_2_array=np.empty(len(beginner_votes_array))
np.floor_divide(beginner_votes_array,2,out=floor_2_array)
print("Dividing all elements by 2(floor)",floor_2_array)
print("\n\n")
print("Negative array",-beginner_votes_array)

Original array: [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Adding 2 to all elements: [656 630 422 654 249 494 489 500 264  69 127  65  78 125  24  74  57 134
  55  55   2  22 372]



Dividing all elements by 2(normal) [327.  314.  210.  326.  123.5 246.  243.5 249.  131.   33.5  62.5  31.5
  38.   61.5  11.   36.   27.5  66.   26.5  26.5   0.   10.  185. ]



Dividing all elements by 2(floor) [327. 314. 210. 326. 123. 246. 243. 249. 131.  33.  62.  31.  38.  61.
  11.  36.  27.  66.  26.  26.   0.  10. 185.]



Negative array [-654 -628 -420 -652 -247 -492 -487 -498 -262  -67 -125  -63  -76 -123
  -22  -72  -55 -132  -53  -53    0  -20 -370]


In [139]:
#Viewing raw numbers does not make much sense instead we would like to know values in percentages
non_professional_votes_array=beginner_votes_array+other_votes_array
non_professional_votes_array_average=round(np.mean(non_professional_votes_array),2)
print("Non professional votes array:",non_professional_votes_array)
print("Non professional votes average:",non_professional_votes_array_average)

Non professional votes array: [1839 1114 1041 1518  640  910  879  828  658  251  292  200  202  313
   88  151  149  201  131  123   31   50 1084]
Non professional votes average: 551.87


In [140]:
#Now we will find which cloud platforms are actually popular(has votes more than average votes)
print("Boolean array for condition if the votes is greater than or equal to average votes:",non_professional_votes_array>=non_professional_votes_array_average)
print("\n\n")
print("Number of cloud platforms which are common:",np.sum(non_professional_votes_array>=non_professional_votes_array_average))
print("\n\n")
print("Number of cloud platforms which have a four digit total votes:",np.sum(non_professional_votes_array>=1000))
print("\n\n")
print("Popular cloud platforms among non professionals:",cloud_2023_array[non_professional_votes_array>=1000])
print("\n\n")
print("Is there any cloud platform that has less than 100 votes?:",np.any(non_professional_votes_array<=100))
print("\n\n")
print("Are all cloud platforms greater than 100 votes?:",np.all(non_professional_votes_array>=100))
print("Cloud platforms which more close towards the average votes:",cloud_2023_array[(non_professional_votes_array>=300) & (non_professional_votes_array<=700)])


Boolean array for condition if the votes is greater than or equal to average votees: [ True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False  True]



Number of cloud platforms which are common: 10



Number of cloud platforms which have a four digit total votes: 5



Popular cloud platforms among non professionals: ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Microsoft Azure']



Is there any cloud platform that has less than 100 votes?: True



Are all cloud platforms greater than 100 votes?: False
Cloud platforms which more close towards the average votes: ['Digital Ocean' 'VMware' 'Oracle Cloud Infrastructure (OCI)']


In [141]:
#Concatenation
new_cloud_platforms=np.array(["ZohoCorpCloud","MyCloudPlatform"])
updated_cloud_2023=np.concatenate([cloud_2023_array,new_cloud_platforms])
print(cloud_2023)
print("\n\n")
print(new_cloud_platforms)
print("\n\n")
print(updated_cloud_2023)

['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare', 'Google Cloud', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway', 'Colocation', 'Microsoft Azure']



['ZohoCorpCloud' 'MyCloudPlatform']



['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean' 'Heroku' 'Vercel' 'Netlify' 'VMware' 'Hetzner'
 'Linode, now Akamai' 'Managed Hosting' 'OVH'
 'Oracle Cloud Infrastructure (OCI)' 'OpenShift' 'Fly.io' 'Vultr' 'Render'
 'OpenStack' 'IBM Cloud Or Watson' 'Scaleway' 'Colocation'
 'Microsoft Azure' 'ZohoCorpCloud' 'MyCloudPlatform']


In [142]:
#For example here the first element of the array is added with the first element of the second array and so on
# 1 and 4 are added (0th element of array 1 and array 2)=5
#2 and 5 are addded (1st element of array 1 and array 2)=7
#3 and 6 are added  (2nd element of array 1 and array 2)=9
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Sum of array 1 and array 2:",arr1+arr2)
#Example: arr1+5 is basically 5 added to all elements of arr1 that means:
arr=np.arange(1,5)
five_array=np.array([5,5,5,5])
print(arr+5)# 5 scalar is expanded to [5,5,5,5] to perform element wise addition(please note this actually does not take place)
print(arr+five_array)

#Broadcasting in multi dimensional single dimensional array operations
#here [[1,2],[3,4]] + [[1,1]]-> [[1,2],[3,4]]+[[1,1],[1,1]] ->[[2,3],[4,5]](again please note this actually does not take place)
arr1=np.array([[1,2],[3,4]])
arr2=[[1,1]]
print("Sum of arr1 and arr2 thanks to broadcasting:",arr1+arr2)

Sum of array 1 and array 2: [5 7 9]
[6 7 8 9]
[6 7 8 9]
Sum of arr1 and arr2 thanks to broadcasting: [[2 3]
 [4 5]]


In [143]:
# Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.


# Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.


# Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
#Illustration for rule 1 and rule 2

#First we see the shape of arr1 is (4,), shape of arr2 is (2,4). The dimension 4 is matching and by rule 1 
#we pad 1 to left side
#arr1 becomes (1,4) in dimension and arr2 is (2,4)
#arr1: [1,2,3,4] -> [[1,2,3,4]] arr2:[[1,2,3,4],[5,6,7,8]]

#Now by rule 2 first dimension is not matching and we stretch the arr1(aray with dimension 1) to match arr2 dimension
#arr1 becomes (2,4) in dimension and arr2 is (2,4) now we can add the arrays
#arr1: [[1,2,3,4]] -> [[1,2,3,4],[1,2,3,4]] arr2:[[1,2,3,4],[5,6,7,8]]

#Now we can add both the arrays
#arr1+arr2:[[1,2,3,4],[1,2,3,4]] + [[1,2,3,4],[5,6,7,8]] -> [[1+1 ,2+2, 3+3,4+4],[1+5,2+6,3+7,4+8]] -> [[2,4,6,8],[6,8,10,12]]
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.shape,arr2.shape)
print(arr2)
print(arr1+arr2)

(4,) (2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  4  6  8]
 [ 6  8 10 12]]


In [144]:
#Illustration for rule 3
#First we see the shape of arr1 is (3,), shape of arr2 is (2,4). The dimension 4 is matching and by rule 1 
#we pad 1 to left side
#arr1 becomes (1,3) in dimension and arr2 is (2,4)
#arr1: [1,2,3] -> [[1,2,3]] arr2:[[1,2,3,4],[5,6,7,8]]

#Now by rule 2 first dimension is not matching and we stretch the arr1(aray with dimension 1) to match arr2 dimension
#arr1 becomes (2,3) in dimension and arr2 is (2,4) now we can add the arrays
#arr1: [[1,2,3]] -> [[1,2,3],[1,2,3]] arr2:[[1,2,3,4],[5,6,7,8]]

#Now the all dimensions do not match and no dimesnion is equal to one.Hence the two arrays can't be added 
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
try:
    print(arr1+arr2)
except:
    print("The arrays can't be broadcasted and hence can't be added")

The arrays can't be broadcasted and hence can't be added


In [145]:
#Let us get a sum aggregate of an array
professional_votes_total=np.add.reduce(professional_votes_array)
beginner_votes_total=np.add.reduce(beginner_votes_array)
other_votes_total=np.add.reduce(other_votes_array)
professional_votes_cummulative_sum=np.add.accumulate(professional_votes_array)
print("Total number of beginners:",beginner_votes_total)
print("\n\n")
print("Total number of professional votes:",professional_votes_total)
print("\n\n")
print("Total number of other votes:",other_votes_total)
print("\n\n")
print("Professional votes array:")
print(professional_votes_array)
print("\n\n")
print("Cummulative sum of professional votes:")
print(professional_votes_cummulative_sum)


Total number of beginners: 5571



Total number of professional votes: 120001



Total number of other votes: [1185 1671 2292 3158 3551 3969 4361 4691 5087 5271 5438 5575 5701 5891
 5957 6036 6130 6199 6277 6347 6378 6408 7122]



Professional votes array:
[29479  8550  8326 13304  7838  6535  5727  4708  3584  2465  2104  1889
  1912  1146  1432  1342  1021   920   802   571   520   385 15441]



Cummulative sum of professional votes:
[ 29479  38029  46355  59659  67497  74032  79759  84467  88051  90516
  92620  94509  96421  97567  98999 100341 101362 102282 103084 103655
 104175 104560 120001]


In [146]:
#let us find which cloud platform has maximum number of votes and minimum number of votes
minimum_votes_number=np.min(total_votes_array)
maximum_votes_number=np.max(total_votes_array)
print(minimum_votes_number,maximum_votes_number)
maximum_votes_index=np.argmax(total_votes_array)
minimum_votes_index=np.argmin(total_votes_array)
print(f"{cloud_2023_array[maximum_votes_index]} is the cloud platform with maximum votes of {maximum_votes_number}")
print(f"{cloud_2023_array[minimum_votes_index]} is the cloud platform with minimum votes of {minimum_votes_number}")

7 33818
Amazon Web Services (AWS) is the cloud platofrm with maximum votes of 33818
Colocation is the cloud platofrm with manimum votes of 7


In [147]:
#Sorting means we arrange the elements in a specific order(mostly ascending or descending order).As usual numpy has a np.sort() 
#which is much faster than sort() in python
total_votes_sorted=np.sort(total_votes_array)
print("Original votes array:",total_votes_array)
print("Sorted total votes array:",total_votes_sorted)

Original votes array: [33818 10761 10599 16592  9299  8358  7431  6228  4964  3069  2755  2379
  2378  1810  1671  1649  1357  1287  1076   801   628     7 18105]
Sorted total votes array: [    7   628   801  1076  1287  1357  1649  1671  1810  2378  2379  2755
  3069  4964  6228  7431  8358  9299 10599 10761 16592 18105 33818]


In [148]:
#Using argsort we can get coressponding indices of elements of the sorted array and sort the cloud_2023 array based on votes
# Get the indices that would sort the total_votes array
sorted_indices_total=np.argsort(total_votes_array)
print("Indexes after sorting the total votes array:")
print(sorted_indices_total)
descending_indexes_total=sorted_indices_total[::-1]
print("Indexes after sorting the total votes array in descending order:")
print(descending_indexes_total)
# Use the indices to sort the cloud_2023 array
cloud_2023_sorted=[cloud_2023[i] for i in descending_indexes_total]

# Print the sorted cloud_2023 array
print("Cloud platforms sorted based on votes:")
print(cloud_2023_sorted)
print("\n\n")

sorted_indexes_professional=np.argsort(professional_votes_array)
descending_indexes_professional=sorted_indexes_professional[::-1]
cloud_2023_sorted_professional=[cloud_2023[i] for i in descending_indexes_professional]
print("Cloud platforms sorted based on votes from Professional programmers:")
print(cloud_2023_sorted_professional)
print("\n\n")

sorted_indexes_beginner=np.argsort(beginner_votes_array)
descending_indexes_beginner=sorted_indexes_beginner[::-1]
cloud_2023_sorted_beginner=[cloud_2023[i] for i in descending_indexes_beginner]
print("Cloud platforms sorted based on votes from Beginner programmers:")
print(cloud_2023_sorted_beginner)


Indexes after sorting the total votes array:
[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  2  1  3 22  0]
Indexes after sorting the total votes array in descending order:
[ 0 22  3  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
Cloud platforms sorted based on votes:
['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud', 'Firebase', 'Cloudflare', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway', 'Colocation']



Cloud platforms sorted based on votes from Professional programmers:
['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud', 'Firebase', 'Cloudflare', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'OVH', 'Managed Hosting', 'OpenShift', 'Fly.io', 'Oracle Cloud Infrastructure (OCI)', 'Vultr', 'Render', '

In [149]:
#Partial sort finds the k-smallest values and places them first in the array and then the remaining elements,the order is random

total_votes_top_4_sort=np.partition(total_votes_array,4)

#First we find the four smallest elements and place them in random order in array 0,1,2,3
#then take remaining elements and put in random order 9,8,7,5,4, Of course for multi dimensional arrays we can sort by dimesnion
print("Partially sorted total votes array for 4 elements:",total_votes_top_4_sort)

Partially sorted total votes array for 4 elements: [    7   628   801  1076  1287  8358  7431  6228  4964  2755  2379  9299
  2378  1810  1671  1649  1357  3069 10599 16592 10761 18105 33818]


In [150]:
# Partial sort finds the k-smallest values and places them first in the array,
# and then the remaining elements in random order

# Get the indices that would partially sort the total_votes array
partial_sort_indices = np.argpartition(total_votes_array, 4)
print("Indexes after partially sorting the total votes array:",partial_sort_indices)

# Use the indices to partially sort the cloud_2023 array
cloud_2023_partially_sorted_4 =[cloud_2023[i] for i in partial_sort_indices[:4]]

# Print the partially sorted cloud_2023 array
print(cloud_2023_partially_sorted_4)

Indexes after partially sorting the total votes array: [21 20 19 18 17  5  6  7  8 10 11  4 12 13 14 15 16  9  2  3  1 22  0]
['Colocation', 'Scaleway', 'IBM Cloud Or Watson', 'OpenStack']
