In [ ]:
#Numpy is an open source package for working with arrays
import numpy
numpy.__version__

'1.23.5'

In [ ]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
l=[True,"String",1,3.2]
print(l)

[True, 'String', 1, 3.2]


1-> this is not an integer this is an object.
python should basically figure what data type it is to store in the memory

In [ ]:
l=[1,2,3,4,5]
arr=np.array(l)
print(l,arr)
print(type(l))
print(type(arr))

[1, 2, 3, 4, 5] [1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# List of cloud technologies in 2023
cloud_2023 = ['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare', 'Google Cloud','Digital Ocean',
               'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH',
               'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack',
               'IBM Cloud Or Watson', 'Scaleway', 'Colocation', 'Microsoft Azure']

#list of all votes for each cloud platform
votes_raw=[33818, 29479, 654, 1185,10761, 8550, 628, 486,10599, 8326, 420, 621,16592, 13304, 652, 866,
9299, 7838, 247, 393,8358, 6535, 492, 418,7431, 5727, 487, 392,6228, 4708, 498, 330,4964, 3584, 262, 396,3069, 2465, 67, 184,
2755, 2104, 125, 167,2379, 1889, 63, 137,2378, 1912, 76, 126,1810, 1146, 123, 190,1671, 1432, 22, 66,1649, 1342, 72, 79,1357, 1021, 55, 94,
1287, 920, 132, 69,1076, 802, 53, 78,801, 571, 53, 70,628, 520, 0, 31,7, 385, 20, 30,18105, 15441, 370, 714]

In [ ]:
print("Data type of votes raw list:",type(votes_raw))

Data type of votes raw list: <class 'list'>


In [ ]:
import numpy as np
cloud_2023_array=np.array(cloud_2023)
votes_2023_array=np.array(votes_raw)
print(cloud_2023_array)
print(votes_2023_array)

['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean' 'Heroku' 'Vercel' 'Netlify' 'VMware' 'Hetzner'
 'Linode, now Akamai' 'Managed Hosting' 'OVH'
 'Oracle Cloud Infrastructure (OCI)' 'OpenShift' 'Fly.io' 'Vultr' 'Render'
 'OpenStack' 'IBM Cloud Or Watson' 'Scaleway' 'Colocation'
 'Microsoft Azure']
[33818 29479   654  1185 10761  8550   628   486 10599  8326   420   621
 16592 13304   652   866  9299  7838   247   393  8358  6535   492   418
  7431  5727   487   392  6228  4708   498   330  4964  3584   262   396
  3069  2465    67   184  2755  2104   125   167  2379  1889    63   137
  2378  1912    76   126  1810  1146   123   190  1671  1432    22    66
  1649  1342    72    79  1357  1021    55    94  1287   920   132    69
  1076   802    53    78   801   571    53    70   628   520     0    31
     7   385    20    30 18105 15441   370   714]


In [ ]:
print(type(cloud_2023_array))

<class 'numpy.ndarray'>


In [ ]:
#size
print("Number of cloud services in the array:",cloud_2023_array.size)
print("The shape of  array:",cloud_2023_array.shape) #(23,)->(23,1)
print("Data types of each element in cloud array:",cloud_2023_array.dtype)#U33 -> String with 33 bytes (Unicode)
print("Data types of each element in the raw votes array:",votes_2023_array.dtype)# int64 -> 64 bit integer
print("umber of dimensions:",votes_2023_array.ndim)

Number of cloud services in the array: 23
The shape of  array: (23,)
Data types of each element in cloud array: <U33
Data types of each element in the raw votes array: int64
umber of dimensions: 1


In [ ]:
#type casting
votes_2023_array_32bit=np.array(votes_2023_array,dtype=np.int32)
votes_2023_array_32bit

array([33818, 29479,   654,  1185, 10761,  8550,   628,   486, 10599,
        8326,   420,   621, 16592, 13304,   652,   866,  9299,  7838,
         247,   393,  8358,  6535,   492,   418,  7431,  5727,   487,
         392,  6228,  4708,   498,   330,  4964,  3584,   262,   396,
        3069,  2465,    67,   184,  2755,  2104,   125,   167,  2379,
        1889,    63,   137,  2378,  1912,    76,   126,  1810,  1146,
         123,   190,  1671,  1432,    22,    66,  1649,  1342,    72,
          79,  1357,  1021,    55,    94,  1287,   920,   132,    69,
        1076,   802,    53,    78,   801,   571,    53,    70,   628,
         520,     0,    31,     7,   385,    20,    30, 18105, 15441,
         370,   714], dtype=int32)

In [ ]:
#upcasting
int64_array=np.array([1.6,0,2,9,True],dtype="int")
int64_array

array([1, 0, 2, 9, 1])

In [ ]:
cloud_2023_array

array(['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare',
       'Google Cloud', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify',
       'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting',
       'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io',
       'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway',
       'Colocation', 'Microsoft Azure'], dtype='<U33')

In [ ]:
votes_2023_array

array([33818, 29479,   654,  1185, 10761,  8550,   628,   486, 10599,
        8326,   420,   621, 16592, 13304,   652,   866,  9299,  7838,
         247,   393,  8358,  6535,   492,   418,  7431,  5727,   487,
         392,  6228,  4708,   498,   330,  4964,  3584,   262,   396,
        3069,  2465,    67,   184,  2755,  2104,   125,   167,  2379,
        1889,    63,   137,  2378,  1912,    76,   126,  1810,  1146,
         123,   190,  1671,  1432,    22,    66,  1649,  1342,    72,
          79,  1357,  1021,    55,    94,  1287,   920,   132,    69,
        1076,   802,    53,    78,   801,   571,    53,    70,   628,
         520,     0,    31,     7,   385,    20,    30, 18105, 15441,
         370,   714])

In [ ]:
#reshape
print(votes_2023_array.shape)

(92,)


In [ ]:
test_array=np.array([33818, 29479, 654,  1185, 10761,  8550,   628,   486])
print(test_array.shape)

(8,)


In [ ]:
reshape_array=np.reshape(test_array,(len(test_array)//4,4))# total number of elements/group size -> len(test_array) divided by 4,4
reshape_array

array([[33818, 29479,   654,  1185],
       [10761,  8550,   628,   486]])

In [ ]:
len(test_array)//4 #quotient as an integer

2.0

In [ ]:
merged_votes_array=np.reshape(votes_2023_array,(len(votes_2023_array)//4,4))
print(merged_votes_array)
print("Shape of the merged votes array:",merged_votes_array.shape)

[[33818 29479   654  1185]
 [10761  8550   628   486]
 [10599  8326   420   621]
 [16592 13304   652   866]
 [ 9299  7838   247   393]
 [ 8358  6535   492   418]
 [ 7431  5727   487   392]
 [ 6228  4708   498   330]
 [ 4964  3584   262   396]
 [ 3069  2465    67   184]
 [ 2755  2104   125   167]
 [ 2379  1889    63   137]
 [ 2378  1912    76   126]
 [ 1810  1146   123   190]
 [ 1671  1432    22    66]
 [ 1649  1342    72    79]
 [ 1357  1021    55    94]
 [ 1287   920   132    69]
 [ 1076   802    53    78]
 [  801   571    53    70]
 [  628   520     0    31]
 [    7   385    20    30]
 [18105 15441   370   714]]
Shape of the merged votes array: (23, 4)


In [ ]:
print("Number of dimensions in merged votes array:",merged_votes_array.ndim)

Number of dimensions in merged votes array: 2


In [ ]:
total_votes_array=merged_votes_array[:,0]
professional_votes_array=merged_votes_array[:,1]
beginner_votes_array=merged_votes_array[:,2]
other_votes_array=merged_votes_array[:,3]
print("Total votes array:",total_votes_array)
print("\n\n")
print("Professional programmers votes",professional_votes_array)
print("\n\n")
print("Beginner programmers votes:",beginner_votes_array)
print("\n\n")
print("Other programmers votes:",other_votes_array)

Total votes array: [33818 10761 10599 16592  9299  8358  7431  6228  4964  3069  2755  2379
  2378  1810  1671  1649  1357  1287  1076   801   628     7 18105]



Professional programmers votes [29479  8550  8326 13304  7838  6535  5727  4708  3584  2465  2104  1889
  1912  1146  1432  1342  1021   920   802   571   520   385 15441]



Beginner programmers votes: [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Other programmers votes: [1185  486  621  866  393  418  392  330  396  184  167  137  126  190
   66   79   94   69   78   70   31   30  714]


In [ ]:
cloud_2023_array

array(['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare',
       'Google Cloud', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify',
       'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting',
       'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io',
       'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway',
       'Colocation', 'Microsoft Azure'], dtype='<U33')

In [ ]:
l=[1,2,3,4,5] #0,1,2,3,4,5
print("first element of the list:",l[0])
print("Elements from second position to fourth position:",l[1:4]) #1,2,3

first element of the list: 1
Elements from second position to fourth position: [2, 3, 4]


In [ ]:
#Corressponding vote values for a random cloud service
print("Cloud service name:",cloud_2023_array[3])
print("Total number of votes:",total_votes_array[3])
print("Professional votes:",professional_votes_array[3])
print("Beginner votes:",beginner_votes_array[3])
print("Other votes:",other_votes_array[3])

Cloud service name: Google Cloud
Total number of votes: 16592
Professional votes: 13304
Beginner votes: 652
Other votes: 866


In [ ]:
print("Cloud service name:",cloud_2023_array[:5]) #0,1,2,3,4
print("Total number of votes:",total_votes_array[:5])
print("Professional votes:",professional_votes_array[:5])
print("Beginner votes:",beginner_votes_array[:5])
print("Other votes:",other_votes_array[:5])

Cloud service name: ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Digital Ocean']
Total number of votes: [33818 10761 10599 16592  9299]
Professional votes: [29479  8550  8326 13304  7838]
Beginner votes: [654 628 420 652 247]
Other votes: [1185  486  621  866  393]


In [ ]:
l=[1,2,3,4,5]
arr=np.array([1,2,3,4,5])
l[0:3][1]=0#elements at index 0,1,2 ->[1,2,3]-> [2]
arr[0:3][1]=0
l,arr

([1, 2, 3, 4, 5], array([1, 0, 3, 4, 5]))

In [ ]:
arr=np.array([1,2,3,4,5])
even_elements_array=arr[0:5:2].copy()#0,2,4
even_elements_array[0]=2
print(arr,even_elements_array)

[1 2 3 4 5] [2 3 5]


In [ ]:
import numpy as np
def compute_non_professional_votes(beginner_votes_array,other_votes_array):
    output = np.empty(len(beginner_votes_array))
    for i in range(len(beginner_votes_array)):
        output[i]=beginner_votes_array[i]+other_votes_array[i]
    return output

%timeit compute_non_professional_votes(beginner_votes_array,other_votes_array)
%timeit (beginner_votes_array+other_votes_array)

In [ ]:
import numpy as np
def compute_non_professional_votes(beginner_votes_array,other_votes_array):
  output=np.empty(len(beginner_votes_array))
  for i in range(len(beginner_votes_array)):#0,1,2,3,4......22 23 is the length of the array which is not included
    output[i]=beginner_votes_array[i]+other_votes_array[i]
  return output
%timeit compute_non_professional_votes(beginner_votes_array,other_votes_array)
%timeit (beginner_votes_array+other_votes_array)

12.6 µs ± 3.72 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
689 ns ± 203 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
#vectorization in umpy arrays and it is implemented in numpy arrays suing Ufuncs(Universal fucntions)
print("Original array:",beginner_votes_array)
print("\n\n")
print("Adding 2  to all elements:",beginner_votes_array+2)
print("\n\n")
print("Divinding all elements by 2(floor)",beginner_votes_array//2)

Original array: [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Adding 2  to all elements: [656 630 422 654 249 494 489 500 264  69 127  65  78 125  24  74  57 134
  55  55   2  22 372]



Divinding all elements by 2(floor) [327 314 210 326 123 246 243 249 131  33  62  31  38  61  11  36  27  66
  26  26   0  10 185]


In [ ]:
print("Adding 2  to all elements:",np.add(beginner_votes_array,2))

Adding 2  to all elements: [656 630 422 654 249 494 489 500 264  69 127  65  78 125  24  74  57 134
  55  55   2  22 372]


In [ ]:
non_professional_votes_array=beginner_votes_array+other_votes_array
non_professional_votes_array_average=round(np.mean(non_professional_votes_array),2)
print("Non professional votes array:",non_professional_votes_array)
print("Non professional votes array average",non_professional_votes_array_average)

Non professional votes array: [1839 1114 1041 1518  640  910  879  828  658  251  292  200  202  313
   88  151  149  201  131  123   31   50 1084]
Non professional votes array average 551.87


In [ ]:
non_professional_votes_array<non_professional_votes_array_average

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [ ]:
np.sum(non_professional_votes_array<non_professional_votes_array_average)

13

In [ ]:
print("Dominant cloud platforms:",cloud_2023_array[non_professional_votes_array>1000])

Dominant cloud platforms: ['Amazon Web Services (AWS)' 'Firebase' 'Cloudflare' 'Google Cloud'
 'Microsoft Azure']


In [ ]:
print("Are all cloud platforms greater than 1000 votes?",np.all(non_professional_votes_array>1000))

Are all cloud platforms greater than 1000 votes? False


In [ ]:
print("Is there any cloud platform with more than 1000 votes?",np.any(non_professional_votes_array>1000))# expression that returns a true or a false value,boolean masking in numpy

Is there any cloud platform with more than 1000 votes? True


In [ ]:
#concatenation
new_cloud_platforms=np.array(["ZohocorpCloud","MyCloudPlatform"])
updated_cloud_2023=np.concatenate([cloud_2023_array,new_cloud_platforms])
updated_cloud_2023

array(['Amazon Web Services (AWS)', 'Firebase', 'Cloudflare',
       'Google Cloud', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify',
       'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting',
       'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io',
       'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway',
       'Colocation', 'Microsoft Azure', 'ZohocorpCloud',
       'MyCloudPlatform'], dtype='<U33')

In [ ]:
print("Total votes array:",total_votes_array)
print("\n\n")
print("Professional programmers votes",professional_votes_array)
print("\n\n")
print("Beginner programmers votes:",beginner_votes_array)
print("\n\n")
print("Other programmers votes:",other_votes_array)

Total votes array: [33818 10761 10599 16592  9299  8358  7431  6228  4964  3069  2755  2379
  2378  1810  1671  1649  1357  1287  1076   801   628     7 18105]



Professional programmers votes [29479  8550  8326 13304  7838  6535  5727  4708  3584  2465  2104  1889
  1912  1146  1432  1342  1021   920   802   571   520   385 15441]



Beginner programmers votes: [654 628 420 652 247 492 487 498 262  67 125  63  76 123  22  72  55 132
  53  53   0  20 370]



Other programmers votes: [1185  486  621  866  393  418  392  330  396  184  167  137  126  190
   66   79   94   69   78   70   31   30  714]


In [ ]:
print("total number of voters in stack overflow:",np.add.reduce(total_votes_array)) #array -> single number

total number of voters in stack overflow: 147022


In [ ]:
print("total number of professionalvoters in stack overflow:",np.add.reduce(total_votes_array))
print("total number of  beginnervoters in stack overflow:",np.add.reduce(beginner_votes_array))
print("total number of  other voters in stack overflow:",np.add.reduce(other_votes_array))

total number of professionalvoters in stack overflow: 147022
total number of  beginnervoters in stack overflow: 5571
total number of  other voters in stack overflow: 7122


In [ ]:
minimum_votes_number=np.min(total_votes_array)
maximum_votes_number=np.max(total_votes_array)
print(minimum_votes_number,maximum_votes_number)
maximum_votes_index=np.argmax(total_votes_array)
minimum_votes_index=np.argmin(total_votes_array)
print(maximum_votes_index,minimum_votes_index)
print(f"{cloud_2023_array[maximum_votes_index]} is the cloud platform with the maxmimum number of votes of {maximum_votes_number}")
print(f"{cloud_2023_array[minimum_votes_index]} is the cloud platform with the minimum number of votes of {minimum_votes_number}")

7 33818
0 21
Amazon Web Services (AWS) is the cloud platform with the maxmimum number of votes of 33818
Colocation is the cloud platform with the minimum number of votes of 7


In [ ]:
total_votes_sorted=np.sort(total_votes_array)
total_votes_sorted

array([    7,   628,   801,  1076,  1287,  1357,  1649,  1671,  1810,
        2378,  2379,  2755,  3069,  4964,  6228,  7431,  8358,  9299,
       10599, 10761, 16592, 18105, 33818])

In [ ]:
sorted_indices_total=np.argsort(total_votes_array)
print("indexes after elements after sorting:")
print(sorted_indices_total)
descending_indexes_total=sorted_indices_total[::-1]
print(descending_indexes_total)
cloud_2023_sorted=[cloud_2023[i] for i in descending_indexes_total]#cloud_2023[0],cloud_2023[22],cloud_2023[3].......cloud_2023[21]
cloud_2023_sorted

indexes after elements after sorting:
[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  2  1  3 22  0]
[ 0 22  3  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


['Amazon Web Services (AWS)',
 'Microsoft Azure',
 'Google Cloud',
 'Firebase',
 'Cloudflare',
 'Digital Ocean',
 'Heroku',
 'Vercel',
 'Netlify',
 'VMware',
 'Hetzner',
 'Linode, now Akamai',
 'Managed Hosting',
 'OVH',
 'Oracle Cloud Infrastructure (OCI)',
 'OpenShift',
 'Fly.io',
 'Vultr',
 'Render',
 'OpenStack',
 'IBM Cloud Or Watson',
 'Scaleway',
 'Colocation']

In [ ]:
sorted_indices_beginner=np.argsort(beginner_votes_array)
print("indexes after elements after sorting:")
print(sorted_indices_beginner)
descending_indexes_beginner=sorted_indices_beginner[::-1]
print(descending_indexes_beginner)
cloud_2023_sorted_beginner=[cloud_2023[i] for i in descending_indexes_beginner]#cloud_2023[0],cloud_2023[22],cloud_2023[3].......cloud_2023[21]
print(cloud_2023_sorted)
print("\n\n")
print(cloud_2023_sorted_beginner)

indexes after elements after sorting:
[20 21 14 19 18 16 11  9 15 12 13 10 17  4  8 22  2  6  5  7  1  3  0]
[ 0  3  1  7  5  6  2 22  8  4 17 10 13 12 15  9 11 16 18 19 14 21 20]
['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud', 'Firebase', 'Cloudflare', 'Digital Ocean', 'Heroku', 'Vercel', 'Netlify', 'VMware', 'Hetzner', 'Linode, now Akamai', 'Managed Hosting', 'OVH', 'Oracle Cloud Infrastructure (OCI)', 'OpenShift', 'Fly.io', 'Vultr', 'Render', 'OpenStack', 'IBM Cloud Or Watson', 'Scaleway', 'Colocation']



['Amazon Web Services (AWS)', 'Google Cloud', 'Firebase', 'Netlify', 'Heroku', 'Vercel', 'Cloudflare', 'Microsoft Azure', 'VMware', 'Digital Ocean', 'Render', 'Linode, now Akamai', 'Oracle Cloud Infrastructure (OCI)', 'OVH', 'Fly.io', 'Hetzner', 'Managed Hosting', 'Vultr', 'OpenStack', 'IBM Cloud Or Watson', 'OpenShift', 'Colocation', 'Scaleway']


In [ ]:
partial_sort_indexes=np.argpartition(total_votes_array,4)
print(partial_sort_indexes)# bottom 4cloud platform
cloud_2023_partially_sorted=[[cloud_2023[i] for i in partial_sort_indexes[:4]]]
cloud_2023_partially_sorted

[21 20 19 18 17  5  6  7  8 10 11  4 12 13 14 15 16  9  2  3  1 22  0]


[['Colocation', 'Scaleway', 'IBM Cloud Or Watson', 'OpenStack']]